baseURL = "https://enguerrand.leclerc.io"
languageCode = "en-us"
title = "Enguerrand Leclerc"

disableKinds = ["taxonomy"]
enableRobotsTXT = true

[params]
  description = "Enguerrand Leclerc is doing UX Design and Front-End development in Paris. Learn a little more about him !"

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  # favicon_ico = "favicon.ico"
  # favicon_ico_sizes = "16x16 32x32"
  # appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"


  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Enguerrand Leclerc"
    # Avatars can be written to images/avatars/
    avatar = "engy.jpg"
    position = "UX Design & Front-End development"
    livesIn = "[Paris, France](https://en.parisinfo.com/)"
    # scope = [
    #     "Product team @ [armstrong](http://byarmstrong.com)"
    #   ]
    biography = """Hey, I’m _Enguerrand_! I’m an __independent programmer__.

I'm __44__, married and father of one 👧🏼 . In my free time I play __videogames__ 🎮  , listen to a [considerable amount](/assets/images/podcast.png) of __podcasts__ 🎙️  (about science, videogames, politics, tech...), and most week-end, you'll find me in front of multiple screens, enjoying __Formula 1__  🏎️ or __Formula E__  🔋 .

I also love __music__ (particularly ambient music and adjacent genres ). Infrequently, I blog about discoveries and favorites at  __[ambientmusicisdead.com](https://ambientmusicisdead.com)__.

For work, I've occupied various positions at __web agencies__ doing web design, web programming, mobile application, etc. In the recent past, I was part of the product team at __[armstrong](http://byarmstrong.com)__ and have cofounded __[revenue studio](https://www.revenue.studio/)__ (Part of [Alphalyr](https://www.alphalyr.com)).

I'm currently available for technology-related project. You can contact me at __enguerrand[at]leclerc[dot]io__ or find me on internet here or there :
"""

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "http://twitter.com/engy"

  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://www.instagram.com/engyii/"

  [[params.social]]
    title = "Facebook"
    icon = "fa-facebook"
    link = "https://www.facebook.com/enguerrand.leclerc"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/enguerrandleclerc/"

  [[params.social]]
    title = "Github"
    icon = "fa-github"
    link = "https://github.com/engyii"

  [[params.social]]
    title = "Dribbble"
    icon = "fa-dribbble"
    link = "https://dribbble.com/engy"

  [[params.social]]
    title = "Behance"
    icon = "fa-behance"
    link = "https://www.behance.net/creativeclouda0f0"

  [[params.social]]
    title = "Vimeo"
    icon = "fa-vimeo"
    link = "https://vimeo.com/enguerrandleclerc"

  [[params.social]]
    title = "Reddit"
    icon = "fa-reddit"
    link = "https://www.reddit.com/user/dinosaurAdventure3d"

  [[params.social]]
    title = "Pinterest"
    icon = "fa-pinterest"
    link = "https://pinterest.com/engyii/"

  [[params.social]]
    title = "Spotify"
    icon = "fa-spotify"
    link = "https://open.spotify.com/user/engy"

  [[params.social]]
    title = "Goodreads"
    icon = "fa-goodreads"
    link = "https://www.goodreads.com/user/show/6720196-engy"

  [[params.social]]
    title = "Youtube"
    icon = "fa-youtube"
    link = "https://www.youtube.com/channel/UCMvexH0W9iitB60onohz_rw"

  [[params.social]]
    title = "Flickr"
    icon = "fa-flickr"
    link = "https://www.flickr.com/people/engytoast/"

    [[params.social]]
    title = "Steam"
    icon = "fa-steam"
    link = "http://steamcommunity.com/id/engy"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Enguerrand Leclerc"

  # Page license
  # [params.license]
  #   link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
  #   name = "CC-BY-SA-4.0"

  # Credits
  # [[params.credits]]
  #   # Title is used as URL text
  #   title = "HTML5UP"
  #   # Text will be used to explain the credit
  #   text = "Design by"
  #   link = "https://html5up.net"